import type { Metadata } from "next";
import { Geologica, IBM_Plex_Sans } from "next/font/google";
import "./styles/index.scss";

// todo add fallback fonts
const geologica = Geologica({
	weight: "800",
	variable: "--font-geologica",
	subsets: ["cyrillic-ext", "latin-ext"],
});

const ibmPlexSans = IBM_Plex_Sans({
	weight: ["400", "600", "700"],
	variable: "--font-ibm_plex_sans",
	subsets: ["cyrillic-ext", "latin-ext"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by industrial next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geologica.variable} ${ibmPlexSans.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
